name: tutorial1
on: push

jobs:
    job1:
        name: job1
        runs-on: ubuntu-latest
        steps:
         - name: setup python
           uses: actions/setup-python@v4
           with: 
              python-version: 3.9
         - name: check python version
           run: python --version

    job2:
        name: job2
        runs-on: windows-latest
        steps:
        - name: step2
          run: |
                echo " hellow from job 2"
                echo  "Today's date: $(date)"

    job3:
        runs-on: ubuntu-latest
        steps:
        - name: step 3
          run: |
                echo "hello from job 3"
                echo  "Today's date: $(date)"
    job4:
        name: job4
        needs: [job1, job2]
        runs-on: ubuntu-latest
        steps:
          - name: step 4
            run: echo "I am job 4"
